### ISSUE TITLE
Remove issue

### ISSUE THREAD

**Issue by dat-archielite** [qh-8/laravel-options#6]
When use `remove()` method in Option. It clean all my `options` table, not only the keys have specified in `remove([])`.

Ex: my `options` table have `key_1`, `key_2`, `key_3`, ...

```php
Option::remove([
    'key_1',
    'key_2',
]);

Option::save();
```

When run this code, it  clean all the `options` table

**Comment by dinhquochan** [comment]
Fixed in #7. Thank @dat-archielite 🥳
